<template>
  <q-page><main class="page-shell"><section class="row items-start justify-between"><div><p class="eyebrow">DECISION SUPPORT</p><h1 class="page-title">Analytics</h1><p class="page-subtitle">Spot delivery patterns before they become schedule problems.</p></div><q-btn flat color="primary" icon="download" label="Export report" no-caps /></section><section class="analytics-grid q-mt-xl"><article class="surface analytics-card analytics-card--wide"><div class="panel-heading"><div><h2>Portfolio completion</h2><p>Tasks completed vs. planned by week</p></div><q-badge color="positive" label="+18% this month" /></div><div class="line-chart"><div v-for="point in completion" :key="point.week" class="line-point" :style="{ height: `${point.value * 2.2}px` }"><span>{{ point.value }}%</span><small>{{ point.week }}</small></div></div></article><article class="surface analytics-card"><div class="panel-heading"><div><h2>Risk mix</h2><p>Current task health</p></div></div><div class="donut-wrap"><div class="donut"><strong>148</strong><span>total tasks</span></div><div class="legend"><span v-for="risk in risks" :key="risk.label"><i :style="{ background: risk.color }"></i>{{ risk.label }} <b>{{ risk.value }}</b></span></div></div></article><article class="surface analytics-card analytics-card--wide"><div class="panel-heading"><div><h2>Delivery confidence</h2><p>How each active project is tracking against its baseline</p></div></div><div v-for="project in confidence" :key="project.name" class="confidence-row"><strong>{{ project.name }}</strong><q-linear-progress rounded size="8px" :value="project.value / 100" :color="project.color" track-color="grey-3" /><span>{{ project.value }}%</span><q-icon :name="project.value > 75 ? 'check_circle' : 'warning'" :color="project.value > 75 ? 'positive' : 'warning'" /></div></article><article class="surface analytics-card"><div class="panel-heading"><div><h2>Planning signals</h2><p>Useful leading indicators</p></div></div><div v-for="signal in signals" :key="signal.label" class="signal"><q-icon :name="signal.icon" :color="signal.color" /><div><strong>{{ signal.value }}</strong><span>{{ signal.label }}</span></div></div></article></section></main></q-page>
</template>
<script setup lang="ts">
const completion = [{ week: 'Jul 15', value: 42 }, { week: 'Jul 22', value: 51 }, { week: 'Jul 29', value: 47 }, { week: 'Aug 05', value: 63 }, { week: 'Aug 12', value: 58 }, { week: 'Aug 19', value: 76 }]
const risks = [{ label: 'On track', value: 75, color: '#0aa77b' }, { label: 'Completed', value: 56, color: '#2a70d6' }, { label: 'At risk', value: 12, color: '#efad27' }, { label: 'Delayed', value: 5, color: '#e25555' }]
const confidence = [{ name: 'Website Revamp', value: 88, color: 'positive' }, { name: 'Mobile App V2', value: 62, color: 'warning' }, { name: 'CRM Integration', value: 34, color: 'negative' }]
const signals = [{ value: '8', label: 'tasks need an owner decision', icon: 'priority_high', color: 'warning' }, { value: '3', label: 'dependencies are blocking work', icon: 'account_tree', color: 'negative' }, { value: '92%', label: 'planned work is staffed', icon: 'groups', color: 'primary' }]
</script>
<style scoped>.eyebrow { color: #7d8ca2; font-size: 10px; font-weight: 700; letter-spacing: 1.3px; margin: 0 0 8px; }.analytics-grid { display: grid; grid-template-columns: 1.25fr .75fr; gap: 18px; }.analytics-card { padding: 24px; }.analytics-card--wide { min-width: 0; }.panel-heading { display: flex; justify-content: space-between; align-items: start; gap: 12px; margin-bottom: 25px; }.panel-heading h2 { font-size: 16px; margin: 0; }.panel-heading p { color: #8996a8; font-size: 12px; margin: 5px 0 0; }.line-chart { height: 220px; display: flex; align-items: end; justify-content: space-around; gap: 16px; border-bottom: 1px solid #e8edf2; background: repeating-linear-gradient(to top, transparent 0, transparent 54px, #f0f3f6 55px); }.line-point { width: min(48px, 11%); min-height: 15px; background: #2a70d6; border-radius: 7px 7px 0 0; position: relative; }.line-point span { position: absolute; top: -22px; left: 50%; transform: translateX(-50%); color: #52708f; font-size: 10px; }.line-point small { position: absolute; top: calc(100% + 10px); left: 50%; transform: translateX(-50%); color: #9aa5b4; font-size: 10px; white-space: nowrap; }.donut-wrap { display: flex; align-items: center; gap: 22px; }.donut { display: grid; place-content: center; width: 135px; height: 135px; border-radius: 50%; background: conic-gradient(#0aa77b 0 51%, #2a70d6 51% 89%, #efad27 89% 97%, #e25555 97%); position: relative; text-align: center; }.donut:after { content: ''; position: absolute; inset: 15px; border-radius: 50%; background: white; }.donut strong, .donut span { position: relative; z-index: 1; }.donut strong { font-family: 'Space Grotesk'; font-size: 22px; }.donut span { color: #8996a8; font-size: 10px; }.legend span { display: block; color: #758398; font-size: 11px; margin: 10px 0; }.legend i { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 7px; }.legend b { color: #26364c; margin-left: 7px; }.confidence-row { display: grid; grid-template-columns: 130px 1fr 38px 20px; align-items: center; gap: 12px; border-top: 1px solid #edf0f3; padding: 15px 0; font-size: 12px; }.confidence-row span { color: #748298; text-align: right; }.signal { display: flex; align-items: center; gap: 14px; padding: 15px 0; border-top: 1px solid #edf0f3; }.signal .q-icon { font-size: 24px; }.signal strong, .signal span { display: block; }.signal strong { font-family: 'Space Grotesk'; font-size: 20px; }.signal span { color: #8996a8; font-size: 11px; margin-top: 3px; }@media (max-width: 900px) { .analytics-grid { grid-template-columns: 1fr; } }@media (max-width: 600px) { .confidence-row { grid-template-columns: 100px 1fr 30px 18px; gap: 7px; font-size: 10px; }.donut-wrap { justify-content: center; } }
</style>
