<template>
  <q-page><main class="page-shell"><section class="row items-start justify-between"><div><p class="eyebrow">PORTFOLIO</p><h1 class="page-title">Projects</h1><p class="page-subtitle">Keep the work visible, prioritized, and moving forward.</p></div><q-btn unelevated color="primary" icon="add" label="New project" no-caps /></section><section class="toolbar surface q-mt-xl"><q-input v-model="search" dense outlined placeholder="Search projects" class="search-input"><template #prepend><q-icon name="search" /></template></q-input><q-select v-model="status" dense outlined :options="['All statuses', 'On track', 'At risk', 'Delayed']" class="status-select" /></section><section class="project-grid q-mt-lg"><article v-for="project in filteredProjects" :key="project.name" class="project-card surface"><div class="project-card__head"><div class="project-symbol" :style="{ background: project.color }">{{ project.short }}</div><q-btn flat round dense icon="more_horiz" /></div><h2>{{ project.name }}</h2><p>{{ project.description }}</p><div class="project-card__status"><q-badge :color="project.statusColor" :label="project.status" /><span>{{ project.deadline }}</span></div><div class="progress-line"><q-linear-progress rounded size="7px" :value="project.progress / 100" :color="project.colorName" track-color="grey-3" /><strong>{{ project.progress }}%</strong></div><div class="project-card__footer"><span><q-icon name="check_circle" /> {{ project.done }} of {{ project.total }} tasks</span><q-btn flat dense color="primary" label="Open" no-caps :to="`/projects/${project.id}`" /></div></article></section></main></q-page>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
const search = ref(''); const status = ref('All statuses')
const projects = [{ id: 'website-revamp', short: 'WR', name: 'Website Revamp', description: 'Refresh the public marketing site and improve conversion paths.', progress: 76, done: 45, total: 60, deadline: 'Due Sep 28', status: 'On track', statusColor: 'positive', color: '#2a70d6', colorName: 'primary' }, { id: 'mobile-app', short: 'MA', name: 'Mobile App V2', description: 'Ship the next mobile release with a faster onboarding experience.', progress: 42, done: 24, total: 60, deadline: 'Due Oct 04', status: 'At risk', statusColor: 'warning', color: '#efad27', colorName: 'warning' }, { id: 'crm-integration', short: 'CI', name: 'CRM Integration', description: 'Connect sales workflows and customer data across the stack.', progress: 23, done: 10, total: 50, deadline: 'Due Sep 30', status: 'Delayed', statusColor: 'negative', color: '#e25555', colorName: 'negative' }, { id: 'brand-system', short: 'BS', name: 'Brand System', description: 'Create a shared component and content language for every team.', progress: 64, done: 32, total: 50, deadline: 'Due Nov 12', status: 'On track', statusColor: 'positive', color: '#0aa77b', colorName: 'positive' }]
const filteredProjects = computed(() => projects.filter((project) => (status.value === 'All statuses' || project.status === status.value) && project.name.toLowerCase().includes(search.value.toLowerCase())))
</script>
<style scoped>.eyebrow { color: #7d8ca2; font-size: 10px; font-weight: 700; letter-spacing: 1.3px; margin: 0 0 8px; }.toolbar { display: flex; gap: 12px; padding: 13px; }.search-input { flex: 1; max-width: 460px; }.status-select { width: 170px; }.project-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }.project-card { padding: 22px; }.project-card__head { display: flex; justify-content: space-between; align-items: start; }.project-symbol { display: grid; place-items: center; width: 40px; height: 40px; border-radius: 10px; color: white; font-weight: 700; font-size: 12px; }.project-card h2 { font-size: 18px; margin: 20px 0 7px; }.project-card p { color: #8996a8; font-size: 12px; line-height: 1.5; min-height: 38px; margin: 0 0 18px; }.project-card__status, .progress-line, .project-card__footer { display: flex; justify-content: space-between; align-items: center; }.project-card__status { color: #8490a1; font-size: 11px; }.progress-line { gap: 12px; margin-top: 18px; }.progress-line .q-linear-progress { flex: 1; }.progress-line strong { font-size: 12px; }.project-card__footer { border-top: 1px solid #edf0f3; margin-top: 20px; padding-top: 14px; color: #7e8da1; font-size: 11px; }.project-card__footer .q-icon { color: #0aa77b; vertical-align: -2px; }@media (max-width: 1000px) { .project-grid { grid-template-columns: repeat(2, 1fr); } }@media (max-width: 600px) { .toolbar { flex-direction: column; }.search-input, .status-select { max-width: none; width: 100%; }.project-grid { grid-template-columns: 1fr; } }</style>
