<template>
  <q-page><main class="page-shell"><section class="row items-start justify-between"><div><p class="eyebrow">EXECUTION QUEUE</p><h1 class="page-title">Tasks</h1><p class="page-subtitle">A single view of everything that needs a decision or a next step.</p></div><q-btn unelevated color="primary" icon="add" label="New task" no-caps /></section><section class="task-summary q-mt-xl"><div v-for="summary in summaries" :key="summary.label" class="summary-item surface"><span :class="`summary-dot summary-dot--${summary.tone}`"></span><div><strong>{{ summary.value }}</strong><small>{{ summary.label }}</small></div></div></section><section class="surface task-table q-mt-lg"><div class="task-toolbar"><q-input v-model="search" dense borderless placeholder="Search tasks"><template #prepend><q-icon name="search" /></template></q-input><q-select v-model="filter" dense outlined :options="['All tasks', 'At risk', 'Due this week']" /></div><q-markup-table flat separator="horizontal"><thead><tr><th align="left">Task</th><th align="left">Project</th><th align="left">Priority</th><th align="left">Owner</th><th align="left">Due</th><th align="left">Status</th></tr></thead><tbody><tr v-for="task in filteredTasks" :key="task.name"><td><strong>{{ task.name }}</strong><small>{{ task.detail }}</small></td><td>{{ task.project }}</td><td><q-badge :color="task.priorityColor" :label="task.priority" /></td><td>{{ task.owner }}</td><td :class="{ 'due-soon': task.status === 'At risk' }">{{ task.due }}</td><td><q-badge outline :color="task.statusColor" :label="task.status" /></td></tr></tbody></q-markup-table></section></main></q-page>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
const search = ref(''); const filter = ref('All tasks')
const summaries = [{ label: 'Open tasks', value: '148', tone: 'blue' }, { label: 'Due this week', value: '15', tone: 'amber' }, { label: 'At risk', value: '8', tone: 'red' }, { label: 'Completed this week', value: '18', tone: 'green' }]
const tasks = [{ name: 'API Integration', detail: 'Connect customer sync endpoint', project: 'CRM Integration', priority: 'Critical', priorityColor: 'negative', owner: 'Sarah Chen', due: 'Today', status: 'At risk', statusColor: 'negative' }, { name: 'Design system audit', detail: 'Review tokens and component coverage', project: 'Website Revamp', priority: 'High', priorityColor: 'warning', owner: 'Maya Patel', due: 'Aug 22', status: 'In progress', statusColor: 'primary' }, { name: 'Database migration', detail: 'Move production records to v2 schema', project: 'Mobile App V2', priority: 'Medium', priorityColor: 'info', owner: 'Alex Johnson', due: 'Aug 25', status: 'In progress', statusColor: 'primary' }, { name: 'Release notes', detail: 'Prepare customer-facing update', project: 'Mobile App V2', priority: 'Low', priorityColor: 'grey-6', owner: 'Marcus Bell', due: 'Aug 28', status: 'Not started', statusColor: 'grey-7' }]
const filteredTasks = computed(() => tasks.filter((task) => (filter.value === 'All tasks' || (filter.value === 'At risk' && task.status === 'At risk') || (filter.value === 'Due this week' && ['Today', 'Aug 22'].includes(task.due))) && `${task.name} ${task.project}`.toLowerCase().includes(search.value.toLowerCase())))
</script>
<style scoped>.eyebrow { color: #7d8ca2; font-size: 10px; font-weight: 700; letter-spacing: 1.3px; margin: 0 0 8px; }.task-summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; }.summary-item { display: flex; align-items: center; gap: 13px; padding: 17px 19px; }.summary-item strong, .summary-item small { display: block; }.summary-item strong { font-family: 'Space Grotesk'; font-size: 22px; }.summary-item small { color: #8996a8; font-size: 11px; margin-top: 3px; }.summary-dot { width: 9px; height: 9px; border-radius: 50%; }.summary-dot--blue { background: #2a70d6; }.summary-dot--amber { background: #efad27; }.summary-dot--red { background: #e25555; }.summary-dot--green { background: #0aa77b; }.task-table { overflow: hidden; }.task-toolbar { display: flex; justify-content: space-between; padding: 15px 20px; border-bottom: 1px solid #e8edf2; }.task-toolbar .q-input { width: 280px; background: #f7f9fb; padding: 0 10px; border-radius: 6px; }.task-toolbar .q-select { width: 150px; }.task-table :deep(th) { color: #8b98a9; font-size: 10px; text-transform: uppercase; letter-spacing: .6px; }.task-table :deep(td) { color: #526176; font-size: 12px; padding: 15px 12px; }.task-table :deep(td:first-child) { color: #1d2c41; }.task-table td strong, .task-table td small { display: block; }.task-table td small { color: #9aa5b4; font-size: 10px; margin-top: 4px; }.due-soon { color: #d54c4c !important; font-weight: 700; }@media (max-width: 700px) { .task-summary { grid-template-columns: repeat(2, 1fr); }.task-table { overflow-x: auto; }.task-toolbar { min-width: 620px; } }</style>
